name: instagram_challenge
description: Re-create instagram app

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/ui/assets/fonts/

  fonts:
    - family: Quicksand
      fonts:
        - asset: lib/ui/assets/fonts/Quicksand-Light.ttf
          weight: 300
        - asset: lib/ui/assets/fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: lib/ui/assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: lib/ui/assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: lib/ui/assets/fonts/Quicksand-Bold.ttf
          weight: 700
