name: instagram_challenge
description: Re-create instagram app

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.0.0
  cloud_firestore: ^1.0.2
  equatable: ^2.0.0
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.2
  firebase_messaging: ^9.0.1
  flutter_local_notifications: ^5.0.0
  flutter_secure_storage: ^4.1.0
  flutter_svg: ^0.21.0-nullsafety.0
  get: ^4.0.0-nullsafety.2
  google_sign_in: ^5.0.1
  lottie: ^1.0.1
  provider: ^5.0.0
  shimmer: ^2.0.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  lint: ^1.5.3

flutter:
  uses-material-design: true

  assets:
    - lib/ui/assets/fonts/
    - lib/ui/assets/icons/broken/
    - lib/ui/assets/icons/bold/
    - lib/ui/assets/icons/brands/
    - lib/ui/assets/images/
    - lib/ui/assets/animations/
    - lib/ui/assets/logo/

  fonts:
    - family: Quicksand
      fonts:
        - asset: lib/ui/assets/fonts/Quicksand-Light.ttf
          weight: 300
        - asset: lib/ui/assets/fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: lib/ui/assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: lib/ui/assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: lib/ui/assets/fonts/Quicksand-Bold.ttf
          weight: 700

flutter_icons:
  image_path: "lib/ui/assets/logo/icon.png"
  android: true
  ios: true
  adaptive_icon_background: "lib/ui/assets/logo/background.png"
  adaptive_icon_foreground: "lib/ui/assets/logo/foreground.png"
