import 'domain/entities/entities.dart';

final UserEntity loggedUser = UserEntity(
  uid: '0',
  username: 'gabrielscota',
  email: 'gabrielscota2015@gmail.com',
  avatar: 'lib/ui/assets/images/avatar-0.png',
  name: 'Gabriel Scotá',
  posts: [],
  createdAt: '',
  updatedAt: '',
  deletedAt: '',
);

final users = <UserEntity>[
  UserEntity(
    uid: '0',
    username: 'gabrielscota',
    email: 'gabrielscota2015@gmail.com',
    avatar: 'lib/ui/assets/images/avatar-0.png',
    name: 'Gabriel Scotá',
    posts: [],
    createdAt: '',
    updatedAt: '',
    deletedAt: '',
  ),
  UserEntity(
    uid: '1',
    username: 'alexis',
    email: 'alexis@gmail.com',
    avatar: 'lib/ui/assets/images/avatar-1.png',
    name: 'Alexis Scott',
    posts: [],
    createdAt: '',
    updatedAt: '',
    deletedAt: '',
  ),
  UserEntity(
    uid: '2',
    username: 'marcus',
    email: 'marcus@gmail.com',
    avatar: 'lib/ui/assets/images/avatar-2.png',
    name: 'Marcus Conner',
    posts: [],
    createdAt: '',
    updatedAt: '',
    deletedAt: '',
  ),
  UserEntity(
    uid: '3',
    username: 'Brian',
    email: 'brian@gmail.com',
    avatar: 'lib/ui/assets/images/avatar-3.png',
    name: 'Brian Spilber',
    posts: [],
    createdAt: '',
    updatedAt: '',
    deletedAt: '',
  ),
  UserEntity(
    uid: '4',
    username: 'julia',
    email: 'julia@gmail.com',
    avatar: 'lib/ui/assets/images/avatar-4.png',
    name: 'Julia Grewn',
    posts: [],
    createdAt: '',
    updatedAt: '',
    deletedAt: '',
  ),
  UserEntity(
    uid: '5',
    username: 'jessica',
    email: 'jessica@gmail.com',
    avatar: 'lib/ui/assets/images/avatar-5.png',
    name: 'Jessica Owen',
    posts: [],
    createdAt: '',
    updatedAt: '',
    deletedAt: '',
  ),
  UserEntity(
    uid: '6',
    username: 'anna',
    email: 'anna@gmail.com',
    avatar: 'lib/ui/assets/images/avatar-6.png',
    name: 'Anna Timber',
    posts: [],
    createdAt: '',
    updatedAt: '',
    deletedAt: '',
  ),
];

final stories = <StorieEntity>[
  StorieEntity(
    uid: '0',
    user: users[1],
    createdAt: '',
    updatedAt: '',
    deletedAt: '',
  ),
  StorieEntity(
    uid: '1',
    user: users[2],
    createdAt: '',
    updatedAt: '',
    deletedAt: '',
  ),
  StorieEntity(
    uid: '2',
    user: users[3],
    createdAt: '',
    updatedAt: '',
    deletedAt: '',
  ),
  StorieEntity(
    uid: '3',
    user: users[4],
    createdAt: '',
    updatedAt: '',
    deletedAt: '',
  ),
  StorieEntity(
    uid: '4',
    user: users[5],
    createdAt: '',
    updatedAt: '',
    deletedAt: '',
  ),
  StorieEntity(
    uid: '5',
    user: users[6],
    createdAt: '',
    updatedAt: '',
    deletedAt: '',
  ),
];

final posts = <PostEntity>[
  PostEntity(
    uid: '0',
    user: users[1],
    subtitle: 'Brasil',
    imageUrl: 'lib/ui/assets/images/post-0.jpg',
    description: 'Description',
    likes: [],
    createdAt: '',
    updatedAt: '',
    deletedAt: '',
  ),
  PostEntity(
    uid: '1',
    user: users[0],
    subtitle: '',
    imageUrl: 'lib/ui/assets/images/post-2.jpg',
    description: 'Description',
    likes: [],
    createdAt: '',
    updatedAt: '',
    deletedAt: '',
  ),
  PostEntity(
    uid: '2',
    user: users[3],
    subtitle: 'Timóteo',
    imageUrl: 'lib/ui/assets/images/post-1.jpg',
    description: 'Description',
    likes: [],
    createdAt: '',
    updatedAt: '',
    deletedAt: '',
  ),
  PostEntity(
    uid: '3',
    user: users[6],
    subtitle: 'EUA',
    imageUrl: 'lib/ui/assets/images/post-3.jpg',
    description: 'Description',
    likes: [],
    createdAt: '',
    updatedAt: '',
    deletedAt: '',
  ),
];
